### PR TITLE
added DANN scoring

### PR DESCRIPTION
**Pull request by davemcg**
make script to pull DANN scoring and convert to vcf for vcfanno use

README cribbing from DANN abstract also included

### CODE REVIEW

**Comment by brentp** [comment]
did you test this? I would be surprised if this works because you're missing the ID, FILTER and QUAL fields in the "VCF".

**Comment by davemcg** [comment]
Uh, yes. I also didn't realize that vcfanno could match by ref / alt on non-vcf files. So you can actually just use the DANN file as is. 

```
dann_file="DANN_whole_genome_SNVs.tsv.bgz"
if [ ! -f $dann_file ]; then
    wget https://cbcl.ics.uci.edu/public_data/DANN/data/DANN_whole_genome_SNVs.tsv.bgz
    wget https://cbcl.ics.uci.edu/public_data/DANN/data/DANN_whole_genome_SNVs.tsv.bgz.tbi
fi
```

scoreset call for `pathoscore.py`
`--scores score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:self`

**Comment by davemcg** [comment]
Let me know if you want me to put another pull request in for the minimal make file. I can also provide a smaller DANN file for testing. It's rather slow to use, since like CADD, it is extremely dense.

**Comment by brentp** [comment]
A PR with the wget and the README would be great. thanks.

**Comment by brentp** [comment]
A PR with the wget and the README would be great. thanks.

**Pull request closed without merging**
