### PR TITLE
README and make.sh for M-CAP, added if statement for grabbing CADD set

### PR DESCRIPTION
**Pull request by jimhavrilla**

### CODE REVIEW

**Comment by brentp** [comment]
is it a VCF? if so, please name it accordingly.

**Comment by jimhavrilla** [comment]
No, it was the only way tabix would work correctly.  It's a 5-field txt
file, like MPC or CADD

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jimhavrilla** [comment]
Also could you check the GERP pull request?

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jimhavrilla** [comment]
I fixed the -p vcf line and made it -b 2 -e 2

**Pull request closed without merging**
