### PR TITLE
add fathmm

### PR DESCRIPTION
**Pull request by qingl0331**
hello, github!

### CODE REVIEW

**Comment by qingl0331** [comment]
Sure, haha!

**Comment by qingl0331** [comment]
done!

**Comment by brentp** [comment]
if you add more recipes, please add them in a separate branch so there is 1 score-set per recipe.

**Comment by qingl0331** [comment]
sure~ thnx!

2017-08-30 14:13 GMT-06:00 Brent Pedersen <notifications@github.com>:

**Pull request merged**
