### PR TITLE
new gene sets and efficiency fixes to old gene formulae

### PR DESCRIPTION
**Pull request by jimhavrilla**

### CODE REVIEW

**Comment by brentp** [comment]
did you mean to commit the actual cancer gene list? we usually only include the recipe.

**Comment by jimhavrilla** [comment]
Yeah that one is custom

**Comment by jimhavrilla** [comment]
I can put it on s3 if you prefer

**Comment by jimhavrilla** [comment]
Hey @brentp other than moving the gene set list to s3, is the PR good?

**Comment by brentp** [comment]
your call. I really don't understand what this is for or why the changes to grep.

**Comment by jimhavrilla** [comment]
Thanks.

We wanted some example gene sets to prerun for clinicians. It took a while
to find some high quality ones. The grep fix is because for some reason the
old formulae only work on Linux not MacOS UNIX. Weirdly enough.

**Pull request merged**
