### PR TITLE
added gnomAD and ExAC scripts, and an example for filtering on allele frequency

### PR DESCRIPTION
**Pull request by jimhavrilla**

### CODE REVIEW

**Comment by jimhavrilla** [comment]
@brentp can you review this PR and merge it please when you have a moment?

**Comment by brentp** [comment]
I prefer to keep the README concise. can you remove the vcfanno config from the readme and just link to af.conf?

I think a 1 sentence blurb above the pathoscore.py annotate command would be sufficient.

**Comment by brentp** [comment]
I would:

+ remove the conf from readme
+ make this a new section under truth sets
+ introduce it with a sentence like: "we know that some supposed pathogenics are not because they appear as common variants in allele-freq databases..." ... you can see how to use this in af.conf (link). And we provide an example of how the gnomAD and ExAC databases could be pre-processes here: (link).

**Comment by jimhavrilla** [comment]
changes have been pushed.  also fixed some typos/formatting in the readme

**Comment by brentp** [comment]
thanks. can you put af.conf in the same directory as the exac script and update the link?

**Comment by jimhavrilla** [comment]
done.

**Pull request merged**
